# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('ar_lat1', models.CharField(max_length=25)),
                ('ar_lon1', models.CharField(max_length=25)),
                ('ar_lat2', models.CharField(max_length=25)),
                ('ar_lon2', models.CharField(max_length=25)),
                ('ar_lat3', models.CharField(max_length=25)),
                ('ar_lon3', models.CharField(max_length=25)),
                ('ar_lat4', models.CharField(max_length=25)),
                ('ar_lon4', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Encontrado',
            fields=[
                ('id_encontrado', models.AutoField(primary_key=True, serialize=False)),
                ('en_fecha', models.CharField(max_length=25)),
                ('en_img', models.FileField(upload_to=b'')),
                ('en_texto', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id_expediente', models.AutoField(primary_key=True, serialize=False)),
                ('ex_estado', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Perdido',
            fields=[
                ('id_perdido', models.AutoField(primary_key=True, serialize=False)),
                ('pe_fecha', models.CharField(max_length=25)),
                ('pe_img', models.FileField(upload_to=b'')),
                ('pe_texto', models.CharField(max_length=140)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appella.Expediente', verbose_name='tiene un')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('us_nombre', models.CharField(max_length=25)),
                ('us_ap_paterno', models.CharField(max_length=25)),
                ('us_ap_materno', models.CharField(max_length=25)),
                ('us_telefono', models.CharField(max_length=20)),
                ('us_imagen', models.FileField(upload_to=b'')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appella.Area', verbose_name='tiene muchos')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('zo_lat', models.CharField(max_length=25)),
                ('zo_lon', models.CharField(max_length=25)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appella.Area', verbose_name='tiene muchos')),
            ],
        ),
        migrations.AddField(
            model_name='perdido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appella.Usuario', verbose_name='tiene muchos'),
        ),
        migrations.AddField(
            model_name='encontrado',
            name='expediente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appella.Expediente', verbose_name='tiene un'),
        ),
        migrations.AddField(
            model_name='encontrado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appella.Usuario', verbose_name='tiene muchos'),
        ),
    ]
