# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appella', '0003_auto_20160202_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encontrado',
            name='en_img',
            field=models.FileField(upload_to='media/%c'),
        ),
        migrations.AlterField(
            model_name='perdido',
            name='pe_img',
            field=models.FileField(upload_to='media/%c'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_img',
            field=models.FileField(upload_to='media/%c'),
        ),
    ]
